// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {game} from '../models';

export function GetState():Promise<game.State>;

export function Guess(arg1:string):Promise<game.State>;

export function NewGame():Promise<game.State>;
