// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Guess(arg1) {
  return window['go']['main']['App']['Guess'](arg1);
}

export function NewGame() {
  return window['go']['main']['App']['NewGame']();
}
